import socket
import json
import requests
import time
import os
from datetime import datetime

# Get configs from environment
LOKI_HOST = os.getenv("LOKI_HOST", "localhost")
LOKI_USERNAME = os.getenv("LOKI_USERNAME")
LOKI_PASSWORD = os.getenv("LOKI_PASSWORD")
LISTEN_PORT = int(os.getenv("LISTEN_PORT", "514"))

# Construct the full push URL
LOKI_URL = f"https://{LOKI_HOST}/loki/api/v1/push"

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(("0.0.0.0", LISTEN_PORT))
print(f"Listening on UDP {LISTEN_PORT}")

while True:
    data, addr = sock.recvfrom(65535)
    log = data.decode(errors='ignore').strip()
    print(f"Received from {addr[0]}: {log}")

    payload = {
        "streams": [
            {
                "labels": f'{{host="{addr[0]}", job="udp-logs"}}',
                "entries": [
                    {
                        "ts": datetime.utcnow().isoformat("T") + "Z",
                        "line": log
                    }
                ]
            }
        ]
    }

    try:
        r = requests.post(
            LOKI_URL,
            auth=(LOKI_USERNAME, LOKI_PASSWORD),
            json=payload,
            timeout=5
        )
        print(f"Loki response: {r.status_code} - {r.text}")
    except Exception as e:
        print(f"Failed to send to Loki: {e}")
