server:
  http_listen_port: ${HTTP_PORT}
  grpc_listen_port: ${GRPC_PORT}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://${LOKI_USERNAME}:${LOKI_PASSWORD}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:${LISTEN_PORT}
      idle_timeout: 60s
      label_structured_data: yes
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
